In [24]:
import pandas as pd

customers = pd.read_csv(
    "../data/synthetic/customers.csv"
)

devices = pd.read_csv(
    "../data/synthetic/devices.csv"
)

customer_devices = pd.read_csv(
    "../data/synthetic/customer_devices.csv"
)

In [25]:
devices.shape

customer_devices.shape

(14216, 3)

In [26]:
devices["device_id"].is_unique

True

In [27]:
customer_devices["customer_id"].nunique()

10000

In [28]:
customer_devices["device_id"].nunique()

14116

In [29]:
invalid_devices = customer_devices[
    ~customer_devices["device_id"].isin(
        devices["device_id"]
    )
]

len(invalid_devices)

0

In [30]:
invalid_customers = customer_devices[
    ~customer_devices["customer_id"].isin(
        customers["customer_id"]
    )
]
len(invalid_customers)

0

In [31]:
customer_devices.groupby(
    "device_id"
).size().sort_values(
    ascending=False
).head(20)

device_id
DEV_011449    7
DEV_004329    7
DEV_001384    7
DEV_012501    7
DEV_007310    7
DEV_000658    7
DEV_003500    6
DEV_003716    6
DEV_011073    5
DEV_002379    5
DEV_003243    5
DEV_012637    4
DEV_011646    4
DEV_007050    4
DEV_010137    4
DEV_009676    4
DEV_004775    4
DEV_010051    4
DEV_006987    4
DEV_011970    3
dtype: int64

In [32]:
shared_device_counts = (
    customer_devices
    .groupby("device_id")["customer_id"]
    .nunique()
)

shared_device_counts[
    shared_device_counts > 1
].sort_values(
    ascending=False
).head(20)

device_id
DEV_000658    7
DEV_007310    7
DEV_012501    7
DEV_011449    7
DEV_004329    7
DEV_001384    7
DEV_003500    6
DEV_003716    6
DEV_002379    5
DEV_011073    5
DEV_003243    5
DEV_011646    4
DEV_010137    4
DEV_010051    4
DEV_009676    4
DEV_006987    4
DEV_007050    4
DEV_004775    4
DEV_012637    4
DEV_009015    3
Name: customer_id, dtype: int64

In [33]:
duplicate_links = customer_devices.duplicated(
    subset=["customer_id", "device_id"]
).sum()

duplicate_links

np.int64(0)

In [34]:
device_id = "DEV_011449"

customer_devices[
    customer_devices["device_id"] == device_id
]

       customer_id   device_id  first_seen
11448  CUST_008130  DEV_011449  2024-12-19
14138  CUST_009655  DEV_011449  2026-01-01
14139  CUST_001520  DEV_011449  2026-01-01
14140  CUST_009126  DEV_011449  2026-01-01
14141  CUST_004558  DEV_011449  2026-01-01
14142  CUST_004507  DEV_011449  2026-01-01
14143  CUST_000435  DEV_011449  2026-01-01

In [35]:
shared_customers = customer_devices[
    customer_devices["device_id"] == device_id
]["customer_id"]

customers[
    customers["customer_id"].isin(shared_customers)
]

,customer_id,country,city,age,account_created_at,kyc_level,account_status
434,CUST_000435,Nigeria,Ibadan,38,2026-04-13,Tier 2,ACTIVE
1519,CUST_001520,Nigeria,Enugu,47,2023-08-19,Tier 2,ACTIVE
4506,CUST_004507,Ghana,Kumasi,43,2024-08-04,Tier 3,SUSPENDED
4557,CUST_004558,Nigeria,Port Harcourt,31,2024-06-28,Tier 3,ACTIVE
8129,CUST_008130,Nigeria,Enugu,25,2024-10-10,Tier 1,ACTIVE
9125,CUST_009126,Ghana,Tamale,40,2024-01-17,Tier 2,ACTIVE
9654,CUST_009655,Ghana,Takoradi,43,2022-09-28,Tier 1,ACTIVE