In [1]:
import pandas as pd

merchants = pd.read_csv(
    "../data/synthetic/merchants.csv"
)

merchants.head()

,merchant_id,merchant_name,country,city,merchant_category,merchant_type,currency,account_created_at,risk_profile
0,MERCH_000001,"Rodriguez, Figueroa and Sanchez",Nigeria,Lagos,Travel & Transport,Physical,NGN,2026-02-02,LOW
1,MERCH_000002,Doyle Ltd,Nigeria,Kano,Retail,Physical,NGN,2025-06-09,LOW
2,MERCH_000003,"Mcclain, Miller and Henderson",Nigeria,Kano,Retail,Physical,NGN,2023-08-10,LOW
3,MERCH_000004,Davis and Sons,Nigeria,Ibadan,E-commerce,Online,NGN,2022-02-22,LOW
4,MERCH_000005,"Guzman, Hoffman and Baldwin",Nigeria,Ibadan,Food & Restaurants,Physical,NGN,2024-10-10,HIGH

In [2]:
merchants.shape

(2000, 9)

In [3]:
merchants["country"].value_counts(
    normalize=True
) * 100

country
Nigeria    74.8
Ghana      25.2
Name: proportion, dtype: float64

In [4]:
merchants["merchant_category"].value_counts(
    normalize=True
) * 100

merchant_category
Retail                   20.25
Food & Restaurants       17.90
E-commerce               12.45
Telecommunications       10.10
Electronics               9.90
Utilities                 7.50
Travel & Transport        6.80
Healthcare                5.65
Professional Services     4.80
Entertainment             4.65
Name: proportion, dtype: float64

In [5]:
merchants["merchant_type"].value_counts(
    normalize=True
) * 100

merchant_type
Physical       54.80
Online         30.95
Marketplace    14.25
Name: proportion, dtype: float64

In [6]:
merchants["risk_profile"].value_counts(
    normalize=True
) * 100

risk_profile
LOW       70.20
MEDIUM    23.35
HIGH       6.45
Name: proportion, dtype: float64

In [7]:
pd.crosstab(
    merchants["country"],
    merchants["currency"]
)

currency  GHS   NGN
country
Ghana     504     0
Nigeria     0  1496