In [17]:
import pandas as pd

profiles = pd.read_csv(
    "../data/synthetic/customer_profiles.csv"
)

customers = pd.read_csv(
    "../data/synthetic/customers.csv"
)

In [24]:
profile_check = profiles.merge(
    customers[
        ["customer_id", "country"]
    ],
    on="customer_id",
    how="left",
)

In [18]:
profiles.shape

(10000, 5)

In [19]:
profiles["activity_profile"].value_counts(
    normalize=True
) * 100

activity_profile
LOW       49.9
MEDIUM    40.3
HIGH       9.8
Name: proportion, dtype: float64

In [20]:
profiles[
    "expected_daily_transactions"
].describe()

count    10000.000000
mean         2.089563
std          2.350317
min          0.200000
25%          0.600000
50%          1.010000
75%          2.830000
max         12.000000
Name: expected_daily_transactions, dtype: float64

In [21]:
profiles[
    "typical_transaction_amount"
].describe()

count     10000.000000
mean      17901.691171
std       29511.549395
min           3.960000
25%        1842.272500
50%        9119.705000
75%       20861.367500
max      485929.420000
Name: typical_transaction_amount, dtype: float64

In [22]:
profiles["currency"].value_counts(
    normalize=True
) * 100

currency
NGN    75.23
GHS    24.77
Name: proportion, dtype: float64

In [23]:
pd.crosstab(
    profiles["currency"],
    customers["country"]
)

country   Ghana  Nigeria
currency
GHS        2477        0
NGN           0     7523

In [25]:
profiles.groupby(
    "currency"
)["typical_transaction_amount"].describe()

,count,mean,std,min,25%,50%,75%,max
currency,,,,,,,,
GHS,2477.0,103.894853,157.686925,3.96,31.34,57.17,111.82,2361.65
NGN,7523.0,23761.739221,31922.832131,850.26,7378.64,13345.38,26715.05,485929.42

In [26]:
profiles.groupby(
    "activity_profile"
)["typical_transaction_amount"].median()

activity_profile
HIGH      42997.83
LOW        6143.80
MEDIUM    16398.10
Name: typical_transaction_amount, dtype: float64

In [27]:
profiles["customer_id"].is_unique

True

In [28]:
profiles["customer_id"].isin(
    customers["customer_id"]
).all()

np.True_